### ISSUE TITLE
command line tool version not correctly identified on non-english locales

### ISSUE THREAD

**Issue by scarlip** [Microsoft/vso-intellij#37]
Android Studio 2.2.2
Visual Studio Team Services 1.107.1
TEE-CLC-14.0.3.zip
Window 7 x86 GERMAN

path to tf executable: selected via "..."
click on "Test" -> The installed version of the TF command line is 0.0.0
expected: correct version should be detected

cause: on German locale, the tf.cmd reports the version as "(Version 14." with capital V, which will not match to `VERSION_PREFIX`

proposal:
`plugin/src/com/microsoft/alm/plugin/external/commands/TfVersionCommand.java:parseOutput(...)`

`-final int start = line.indexOf(VERSION_PREFIX);`
`+String lowerLine = line.toLowerCase();`
`+final int start = lowerLine.indexOf(VERSION_PREFIX);`

**Comment by jpricketMSFT** [comment]
@scarlip - Thanks for digging in and figuring out the bug here. We will get this fixed for the next release.
Thanks,
Jason

**Comment by jpricketMSFT** [comment]
I made the code change and it should go out with the next release. Note that the real problem is that we haven't made all the changes needed so that we can get the output from the command line parsed no matter the locale. So, we have also made a change that forces the locale of the command line (when called by IntelliJ) to use en-US. This is not the final answer, but should keep everyone from being blocked by older versions of the TF command line.
