### ISSUE TITLE
Visual Studio Team Services Plugin problem in Guidewire Studio

### ISSUE THREAD

**Issue by SumanMarri** [Microsoft/vso-intellij#42]
Hi,

I have problems while installing Visual Studio Team Services Plugin in guidewire studio. Does intellij support this plugin in guidewire studio?

![image](https://cloud.githubusercontent.com/assets/18200000/20156097/b941c456-a683-11e6-9de9-10602581bb83.png)
![image](https://cloud.githubusercontent.com/assets/18200000/20156126/d9ea5ee8-a683-11e6-890c-1f01c6b6faf1.png)

**Comment by leantk** [comment]
Hi @SumanMarri,

Thanks for posting the issue! I have not seen this error before but usually our plug-in is compatible with all IntelliJ IDE types. I'm sorry to say I can't find a Guidewire Studio link to download anywhere online so I can't try it out myself (if you know of one, please let me know). Something looks extremely wrong though with the loading of the plugin. Would you be able to get me the full log from the IDE please? Reproduce the error again. If this follows IntelliJ standards, you should be able to go to Help-> Show Log in Explorer. Zip up the latest idea.log file there and attach it to this Issue. I can see if the plugin had a problem earlier loading that then caused this error to occur.

Thanks,
-Leah

**Comment by SumanMarri** [comment]
Hi @leantk 


Thanks for responding, studio is guidewire so you may not find in online. i attached the error log. 
[pluginError.txt](https://github.com/Microsoft/vso-intellij/files/584249/pluginError.txt)

**Comment by leantk** [comment]
Thanks for the log. I'm not sure why it isn't finding the class so I'm wondering if the plugin zip file that was uploaded is messed up in some way. Would you mind trying out this updated version of the plugin out to see if you get the same error? To install this, go to the Plugin tab in Settings like you did before but select "Install plugin from disk" and select this zip file. 

Also, are you using this with another language other than English? It's the localization service that isn't found which deals with translations to other languages. Since we haven't seen this before, I'm trying to figure out what may be different on your setup other than the Guidwire Studio version of IntelliJ.

[plugin.idea-1.107.2.zip](https://github.com/Microsoft/vso-intellij/files/584457/plugin.idea-1.107.2.zip)

**Comment by leantk** [comment]
Thanks for the log. I'm not sure why it isn't finding the class so I'm wondering if the plugin zip file that was uploaded is messed up in some way. Would you mind trying out this updated version of the plugin out to see if you get the same error? To install this, go to the Plugin tab in Settings like you did before but select "Install plugin from disk" and select this zip file. 

Also, are you using this with another language other than English? It's the localization service that isn't found which deals with translations to other languages. Since we haven't seen this before, I'm trying to figure out what may be different on your setup other than the Guidwire Studio version of IntelliJ.

[plugin.idea-1.107.2.zip](https://github.com/Microsoft/vso-intellij/files/584457/plugin.idea-1.107.2.zip)

**Comment by SumanMarri** [comment]
grabbed new copy of studio and then installed this plugin and it worked. Thank you @leantk
