### ISSUE TITLE
Grey unclickable icon and extra tabs (IDEA)

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#59]
Hi!

My project is not under VCS, but when the plugin is installed and enabled, an unclickable icon appears in IDEA's status bar.
If my project is under VCS, but not Team Services Git/TFVC, there are Pull Requests/Work Items tabs in the Version Control tool window.
Could you please hide all of them in such cases? 
![2017-03-07_15-44-41](https://cloud.githubusercontent.com/assets/22168773/23657036/3a0060d6-034d-11e7-88e3-5a8d68d211d7.png)

**Comment by leantk** [comment]
Hi @bubblef,

Thanks for the suggestions. I see why that would be bothersome if you weren't using a Team Services repository but could see the icons for it. I will add this to our backlog to fix. I'll keep this issue open and update it when the work is done and released.

Thanks again for reaching out,
-Leah

**Comment by bubblef** [comment]
Thank you!

**Comment by leantk** [comment]
Hi @bubblef,

I made the change in commit https://github.com/Microsoft/vso-intellij/commit/e204b0bffe12e64793958b4dedcb5f458b993933 to hide the tab/icon in Rider. In the case where the plugin would be pre-installed, hiding them makes perfect sense since they won't necessarily be using VSTS. When the plugin is manually installed in other IDEs we can assume they have a VSTS account and give them the option to import non-VSTS repos with those tabs.

I'll keep this issue open until I release the change so it can be tracked.

Thanks,
-Leah

**Comment by bubblef** [comment]
Hi Leah,
Thanks for the fix. I checked it in 1.115.2. The tabs/the icon are hided, but I noticed this icon in Commit Changes dialog. Could you please hide it too?
![2017-03-16_17-30-57](https://cloud.githubusercontent.com/assets/22168773/24005047/fb4554e0-0a78-11e7-9680-9462712787a5.png)

**Comment by leantk** [comment]
Yep good catch. I forgot about that. I hid it in this commit https://github.com/Microsoft/vso-intellij/commit/895b0951497d0ee516786632be66263f3ff041e8

**Comment by leantk** [comment]
The fixes for this have been released so I'm closing this issue. If you still are able to see VSTS icons in non-VSTS projects please feel free to reopen this.
