### ISSUE TITLE
Exception occurs in plugin after authorization (IDEA)

### ISSUE THREAD

**Issue by bubblef** [Microsoft/vso-intellij#61]
Hi,

When the window "Import project into Team services" is opened, this exception occurs
`com.intellij.ide.ui.laf.darcula.DarculaUIUtil.paintFocusRing(Ljava/awt/Graphics;IIII)V
java.lang.NoSuchMethodError: com.intellij.ide.ui.laf.darcula.DarculaUIUtil.paintFocusRing(Ljava/awt/Graphics;IIII)V
at com.microsoft.alm.plugin.idea.common.ui.controls.Hyperlink.paintComponent(Hyperlink.java:80)`
Steps: Open a project, VCS > Import into Team Services Git

[stacktrace.txt](https://github.com/Microsoft/vso-intellij/files/830254/stacktrace.txt)

**Comment by leantk** [comment]
Hi @bubblef,

What version of IDEA are you using? I haven't seen this issue with the 2016 version but I just installed 2017 and I see the same exception. It looks like a method we were calling was removed in the new version so thanks for catching that. This is pretty serious so I'll work on getting the fix in ASAP. I'll update this issue when the fix is released.

Thanks,
-Leah

**Comment by leantk** [comment]
The fix for this was made in commit https://github.com/Microsoft/vso-intellij/commit/cf0ef2b68d130e98be18af97a1c7e53ba0719974

**Comment by leantk** [comment]
I just released version 1.115.1 of the plugin with the fix. Please let me know if that fixes your issue.

Thanks!
-Leah

**Comment by bubblef** [comment]
Hi Leah,
I don't have this exception in the latest version. Thanks for the quick fix.
