### ISSUE TITLE
Cant see TFVC option under VCS in new Android Studio

### ISSUE THREAD

**Issue by mahmed1987** [Microsoft/vso-intellij#64]
I updated my android studio . It was a major update since it took like half an hour. my Android studio version is 2.3. Here are the more verbose details of the version I am running.

Android Studio 2.3
Build #AI-162.3764568, built on February 24, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I installed the latest plugin for Team foundation services via the Plugins option under Settings. The plugin version is 1.115.2. 

I am unable to see the TFVC option under VCS 
![as](https://cloud.githubusercontent.com/assets/26518062/24079259/fc675fe6-0c9c-11e7-944f-f6cb506fc40f.png)

![as1](https://cloud.githubusercontent.com/assets/26518062/24079266/1c528b8c-0c9d-11e7-9c95-d8fc94db0398.png)

**Comment by leantk** [comment]
Hi @mahmed1987,

The TFVC menu only appears when a TFVC project is open. Android Studio is identifying your current project as Subversion instead of TFVC. That's why the menu isn't there. If this project truly is TFVC and not Subversion, you can open the vcs.xml file under the .idea directory and make the change there. You will see the line _<mapping directory="" vcs="Subversion" />_ (or something like that) which needs to be changed to _<mapping directory="" vcs="TFVC" />_ Let me know if that works and the TFVC menu appears again.

Thanks,
-Leah

**Comment by leantk** [comment]
Closing since there has been no follow-up. Please reopen if the issue still persists.

Thanks,
-Leah
