### ISSUE TITLE
Server name URL was not recognized...

### ISSUE THREAD

**Issue by arcticwhite** [Microsoft/vso-intellij#80]
I'm getting this error after connecting to TFS in Android Studio.

It's not listing any repository. And the error is "The server URL was not recognized. Make sure it does not contain a collection or repository name.

My version of Visual Studio Team Services is v1.116.1
You can see my URL on the image.
![untitled](https://cloud.githubusercontent.com/assets/23723816/26056515/f9e28b46-3975-11e7-8ec0-7f9665ccdf88.png)

**Comment by AlexRukhlin** [comment]
Hi @arcticwhite

Could you please collect a Fiddler trace for this issue?

Alex

**Comment by arcticwhite** [comment]
Hello @AlexRukhlin 

My Fiddler doesn't show any traffic while logging with my credentials in the same window...
And it doesn't show any traffic after getting to this, same window.

**Comment by leantk** [comment]
Hi @arcticwhite,

Instead of the Fiddler trace could you please give me a log from Android Studio? You can follow the last FAQ here to see how to get it: http://java.visualstudio.com/Docs/tools/androidStudio#_frequently-asked-questions-faq

If you don't want to post your log here feel free to email it to me directly at leantk@microsoft.com

Thanks,
-Leah

**Comment by arcticwhite** [comment]
With one of latest builds/releases this has been resolved...
