### ISSUE TITLE
Error:KEY_TF_BAD_EXIT_CODE when updating the project

### ISSUE THREAD

**Issue by julia-vaseva** [Microsoft/vso-intellij#90]
Please find logs attached.
[idea.zip](https://github.com/Microsoft/vso-intellij/files/1183644/idea.zip)

**Comment by leantk** [comment]
Hi @julia-vaseva,

Your workspace can't be identified by the plugin. I'm trying to figure out why. Did you create the workspace with the Jetbrains TFS plugin or the our TFVC? Is is a server workspace?

Also we should be giving a better error message as to what's happening so I'll add that to our backlog. 

Thanks,
-Leah

**Comment by julia-vaseva** [comment]
Hi @leantk,

This is a log file send by our user. Unfortunately, I haven't got any steps to reproduce the issue. It is definitely your TFVC plugin, and, as far as I understand, the user tries to use a workspace created via Visual Studio: "I am trying to open a solution which is already bound using Visual Studio."

Sorry for such a poor description, hope that it'll help to localize the problem anyway.

**Comment by leantk** [comment]
Currently workspaces created in Visual Studio cannot be identified with the command line tool that is used by the plugin. That is why the user is seeing that error. The user would have to clone the repository using our plugin or the command line tool in order to use the other plugin features.

Like I said, I will make a fix to show a proper error message but as for making Visual Studio workspaces compatible with our plugin, that's a very large change that we aren't able to get to at the moment. There is a backlog item for it though.

**Comment by julia-vaseva** [comment]
@leantk Thanks for clarifying and for showing a workaround! I believe that an error message is always a good idea. Shouldn't we mention in [docs](http://java.visualstudio.com/Docs/tools/intelliJ), that VS workspaces won't work with this plugin out-of-the-box?

**Comment by leantk** [comment]
Yes I should have that in the docs for sure. Thanks for pointing that out. I'll add the error message and updates to the doc and then let you know when that's complete.

**Comment by leantk** [comment]
I've updated the error messaging in commit https://github.com/Microsoft/vso-intellij/commit/0c66406c641b9b912da268f3587d0fdf5c5b5dd9 to be more informative and I've also updated the website with the information on how to recognize Visual Studio workspaces. I'll close this as fixed but please reopen if you see more issues.
